# Generated by Django 6.0.4 on 2026-05-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_settlement_payment_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlementpayment',
            options={'ordering': ['created_at']},
        ),
    ]
